import type { WordInput } from "./types";

type Sample = Omit<WordInput, "isFavorite" | "notes"> & { isFavorite?: boolean; notes?: string };

const S = (w: Sample): WordInput => ({ notes: "", isFavorite: false, ...w });

export const SAMPLE_WORDS: WordInput[] = [
  S({ word: "Abate", pronunciation: "/əˈbeɪt/", partOfSpeech: "verb", banglaMeaning: "কমে যাওয়া; প্রশমিত হওয়া", englishMeaning: "To become less intense or widespread.", synonyms: ["subside", "diminish", "wane", "decrease"], antonyms: ["intensify", "escalate", "increase"], example: "The storm finally abated after midnight.", prefix: "a- (to)", rootWord: "battre (to beat)", suffix: "", mnemonic: "A bat ate the noise — so the noise abated.", etymology: "Old French abatre, 'to beat down'.", tags: ["GRE"], difficulty: "medium" }),
  S({ word: "Benevolent", pronunciation: "/bəˈnev.əl.ənt/", partOfSpeech: "adjective", banglaMeaning: "দয়ালু; পরোপকারী", englishMeaning: "Well meaning and kindly; disposed to do good.", synonyms: ["kind", "generous", "charitable", "compassionate"], antonyms: ["malevolent", "cruel", "unkind"], example: "A benevolent donor paid for the children's education.", prefix: "bene- (well)", rootWord: "vol (wish)", suffix: "-ent (having the quality of)", mnemonic: "BENE = good (as in 'benefit') + VOL = wish → wishing good for others.", etymology: "Latin bene volent-, 'well wishing'.", tags: ["GRE", "IELTS"], difficulty: "medium", isFavorite: true }),
  S({ word: "Candid", pronunciation: "/ˈkæn.dɪd/", partOfSpeech: "adjective", banglaMeaning: "অকপট; স্পষ্টবাদী", englishMeaning: "Truthful and straightforward; frank.", synonyms: ["frank", "honest", "open", "sincere"], antonyms: ["evasive", "guarded", "deceitful"], example: "She gave a candid account of her mistakes.", prefix: "", rootWord: "cand (to shine, white)", suffix: "-id", mnemonic: "A CANDID camera shows the truth exactly as it is.", etymology: "Latin candidus, 'white, pure'.", tags: ["IELTS"], difficulty: "easy" }),
  S({ word: "Diligent", pronunciation: "/ˈdɪl.ɪ.dʒənt/", partOfSpeech: "adjective", banglaMeaning: "পরিশ্রমী; অধ্যবসায়ী", englishMeaning: "Having or showing care and conscientiousness in one's work or duties.", synonyms: ["hardworking", "industrious", "assiduous", "meticulous"], antonyms: ["lazy", "negligent", "idle"], example: "The diligent student reviewed her notes every evening.", prefix: "di- (apart)", rootWord: "leg (to choose)", suffix: "-ent", mnemonic: "DILI-GENT: a gent who works DAILY.", etymology: "Latin diligere, 'to value highly'.", tags: ["IELTS", "SAT"], difficulty: "easy" }),
  S({ word: "Ephemeral", pronunciation: "/ɪˈfem.ər.əl/", partOfSpeech: "adjective", banglaMeaning: "ক্ষণস্থায়ী", englishMeaning: "Lasting for a very short time.", synonyms: ["transient", "fleeting", "momentary", "short-lived"], antonyms: ["permanent", "enduring", "eternal"], example: "Fame on social media is often ephemeral.", prefix: "epi- (upon)", rootWord: "hemera (day)", suffix: "-al", mnemonic: "EPHEMERAL = lasting only 'a day' (hemera = day).", etymology: "Greek ephēmeros, 'lasting only a day'.", tags: ["GRE"], difficulty: "hard", isFavorite: true }),
  S({ word: "Frugal", pronunciation: "/ˈfruː.ɡəl/", partOfSpeech: "adjective", banglaMeaning: "মিতব্যয়ী", englishMeaning: "Sparing or economical with regard to money or food.", synonyms: ["thrifty", "economical", "prudent", "sparing"], antonyms: ["extravagant", "wasteful", "lavish"], example: "Living a frugal life helped him save for a house.", prefix: "", rootWord: "frux (fruit, profit)", suffix: "-al", mnemonic: "FRUGAL people eat FRUIT instead of fancy meals.", etymology: "Latin frugalis, 'virtuous, thrifty'.", tags: ["SAT"], difficulty: "easy" }),
  S({ word: "Gregarious", pronunciation: "/ɡrɪˈɡeə.ri.əs/", partOfSpeech: "adjective", banglaMeaning: "মিশুক; সঙ্গপ্রিয়", englishMeaning: "Fond of company; sociable.", synonyms: ["sociable", "outgoing", "friendly", "convivial"], antonyms: ["introverted", "reserved", "unsociable"], example: "Her gregarious nature made her popular at parties.", prefix: "", rootWord: "greg (flock, herd)", suffix: "-ious (full of)", mnemonic: "GREG is GREGARIOUS — always with the flock.", etymology: "Latin gregarius, from grex 'flock'.", tags: ["GRE", "IELTS"], difficulty: "medium" }),
  S({ word: "Hackneyed", pronunciation: "/ˈhæk.nid/", partOfSpeech: "adjective", banglaMeaning: "গতানুগতিক; বহুল ব্যবহারে জীর্ণ", englishMeaning: "Lacking significance through having been overused; unoriginal.", synonyms: ["clichéd", "trite", "overused", "stale"], antonyms: ["original", "fresh", "novel"], example: "The movie's plot was full of hackneyed phrases.", prefix: "", rootWord: "hackney (a horse for hire)", suffix: "-ed", mnemonic: "A HACKNEY carriage was used by everyone — overused, just like HACKNEYED phrases.", etymology: "From Hackney, London, known for horses for hire.", tags: ["GRE"], difficulty: "hard" }),
  S({ word: "Impeccable", pronunciation: "/ɪmˈpek.ə.bəl/", partOfSpeech: "adjective", banglaMeaning: "নিখুঁত; ত্রুটিহীন", englishMeaning: "In accordance with the highest standards; faultless.", synonyms: ["flawless", "perfect", "faultless", "immaculate"], antonyms: ["flawed", "imperfect", "defective"], example: "He has impeccable manners.", prefix: "im- (not)", rootWord: "pecc (sin)", suffix: "-able", mnemonic: "IM-PECC-ABLE: not able to sin → perfect.", etymology: "Latin impeccabilis, 'not liable to sin'.", tags: ["IELTS"], difficulty: "medium", isFavorite: true }),
  S({ word: "Jubilant", pronunciation: "/ˈdʒuː.bɪ.lənt/", partOfSpeech: "adjective", banglaMeaning: "উল্লসিত; আনন্দে উচ্ছ্বসিত", englishMeaning: "Feeling or expressing great happiness and triumph.", synonyms: ["joyful", "elated", "exultant", "overjoyed"], antonyms: ["sad", "dejected", "despondent"], example: "The jubilant fans celebrated the victory all night.", prefix: "", rootWord: "jubil (to shout for joy)", suffix: "-ant", mnemonic: "JUBILANT like a JUBILEE celebration.", etymology: "Latin jubilare, 'to shout for joy'.", tags: ["SAT"], difficulty: "easy" }),
  S({ word: "Kindle", pronunciation: "/ˈkɪn.dəl/", partOfSpeech: "verb", banglaMeaning: "প্রজ্বলিত করা; জাগিয়ে তোলা", englishMeaning: "To light a fire; to arouse or inspire an emotion or interest.", synonyms: ["ignite", "spark", "arouse", "inspire"], antonyms: ["extinguish", "quench", "dampen"], example: "The teacher kindled her interest in science.", prefix: "", rootWord: "", suffix: "", mnemonic: "A KINDLE e-reader KINDLES your love for reading.", etymology: "Old Norse kynda, 'to set on fire'.", tags: ["IELTS"], difficulty: "easy" }),
  S({ word: "Lucid", pronunciation: "/ˈluː.sɪd/", partOfSpeech: "adjective", banglaMeaning: "প্রাঞ্জল; সুস্পষ্ট", englishMeaning: "Expressed clearly; easy to understand.", synonyms: ["clear", "coherent", "articulate", "transparent"], antonyms: ["confusing", "obscure", "vague"], example: "She gave a lucid explanation of the theory.", prefix: "", rootWord: "luc (light)", suffix: "-id", mnemonic: "LUC = light; a LUCID idea is full of light.", etymology: "Latin lucidus, 'bright, clear'.", tags: ["GRE", "IELTS"], difficulty: "medium" }),
  S({ word: "Meticulous", pronunciation: "/məˈtɪk.jə.ləs/", partOfSpeech: "adjective", banglaMeaning: "অতি যত্নশীল; খুঁটিনাটিতে সতর্ক", englishMeaning: "Showing great attention to detail; very careful and precise.", synonyms: ["careful", "precise", "thorough", "scrupulous"], antonyms: ["careless", "sloppy", "negligent"], example: "The meticulous editor caught every single typo.", prefix: "", rootWord: "metus (fear)", suffix: "-ulous (full of)", mnemonic: "METICULOUS people MEASURE every TICK.", etymology: "Latin meticulosus, 'fearful'.", tags: ["IELTS", "SAT"], difficulty: "medium" }),
  S({ word: "Nostalgia", pronunciation: "/nɒsˈtæl.dʒə/", partOfSpeech: "noun", banglaMeaning: "অতীতের স্মৃতিকাতরতা", englishMeaning: "A sentimental longing or wistful affection for the past.", synonyms: ["reminiscence", "longing", "wistfulness", "yearning"], antonyms: ["indifference", "apathy"], example: "Old songs fill me with nostalgia.", prefix: "", rootWord: "nostos (return home)", suffix: "-algia (pain)", mnemonic: "NOST-ALGIA: the 'pain' (algia) of wanting to return home (nostos).", etymology: "Greek nostos 'homecoming' + algos 'pain'.", tags: ["IELTS"], difficulty: "easy" }),
  S({ word: "Obsolete", pronunciation: "/ˌɒb.səlˈiːt/", partOfSpeech: "adjective", banglaMeaning: "অপ্রচলিত; সেকেলে", englishMeaning: "No longer produced or used; out of date.", synonyms: ["outdated", "antiquated", "archaic", "outmoded"], antonyms: ["modern", "current", "contemporary"], example: "Typewriters became obsolete with the rise of computers.", prefix: "ob- (away)", rootWord: "solere (to be accustomed)", suffix: "-ete", mnemonic: "OBSOLETE — 'Oh, it's SO LATE' for that technology.", etymology: "Latin obsoletus, 'grown old, worn out'.", tags: ["SAT"], difficulty: "easy" }),
  S({ word: "Pragmatic", pronunciation: "/præɡˈmæt.ɪk/", partOfSpeech: "adjective", banglaMeaning: "বাস্তববাদী; ব্যবহারিক", englishMeaning: "Dealing with things sensibly and realistically.", synonyms: ["practical", "realistic", "sensible", "down-to-earth"], antonyms: ["idealistic", "impractical", "unrealistic"], example: "We need a pragmatic solution, not a perfect one.", prefix: "", rootWord: "pragma (deed, act)", suffix: "-tic", mnemonic: "PRAGMATIC people are PRACTICAL.", etymology: "Greek pragmatikos, 'fit for action'.", tags: ["GRE", "IELTS"], difficulty: "medium", isFavorite: true }),
  S({ word: "Quell", pronunciation: "/kwel/", partOfSpeech: "verb", banglaMeaning: "দমন করা; প্রশমিত করা", englishMeaning: "To put an end to a rebellion or disorder; to suppress a feeling.", synonyms: ["suppress", "subdue", "crush", "calm"], antonyms: ["incite", "provoke", "instigate"], example: "The police quelled the riot within hours.", prefix: "", rootWord: "", suffix: "", mnemonic: "QUELL the yell — quiet it down.", etymology: "Old English cwellan, 'to kill'.", tags: ["GRE"], difficulty: "medium" }),
  S({ word: "Resilient", pronunciation: "/rɪˈzɪl.i.ənt/", partOfSpeech: "adjective", banglaMeaning: "স্থিতিস্থাপক; দ্রুত ঘুরে দাঁড়াতে সক্ষম", englishMeaning: "Able to recover quickly from difficulties; tough.", synonyms: ["tough", "hardy", "strong", "adaptable"], antonyms: ["fragile", "vulnerable", "weak"], example: "Children are often remarkably resilient.", prefix: "re- (back)", rootWord: "salire (to jump)", suffix: "-ent", mnemonic: "RE-SILIENT: jumps back (re + salire) after every fall.", etymology: "Latin resilire, 'to leap back'.", tags: ["IELTS"], difficulty: "medium" }),
  S({ word: "Scrutinize", pronunciation: "/ˈskruː.tɪ.naɪz/", partOfSpeech: "verb", banglaMeaning: "খুঁটিয়ে পরীক্ষা করা", englishMeaning: "To examine or inspect closely and thoroughly.", synonyms: ["examine", "inspect", "analyze", "study"], antonyms: ["ignore", "overlook", "neglect"], example: "The auditor scrutinized every transaction.", prefix: "", rootWord: "scrutinium (search)", suffix: "-ize (to make)", mnemonic: "SCRUTINIZE — SCREW up your eyes to see every detail.", etymology: "Latin scrutari, 'to search, examine'.", tags: ["IELTS", "SAT"], difficulty: "medium" }),
  S({ word: "Tenacious", pronunciation: "/təˈneɪ.ʃəs/", partOfSpeech: "adjective", banglaMeaning: "নাছোড়বান্দা; দৃঢ়প্রতিজ্ঞ", englishMeaning: "Tending to keep a firm hold; very determined and persistent.", synonyms: ["persistent", "determined", "resolute", "steadfast"], antonyms: ["irresolute", "weak", "yielding"], example: "Her tenacious effort finally paid off.", prefix: "", rootWord: "ten (to hold)", suffix: "-acious (inclined to)", mnemonic: "TEN-acious: holds on for TEN rounds.", etymology: "Latin tenax, 'holding fast'.", tags: ["GRE"], difficulty: "hard" }),
  S({ word: "Ubiquitous", pronunciation: "/juːˈbɪk.wɪ.təs/", partOfSpeech: "adjective", banglaMeaning: "সর্বব্যাপী; সর্বত্র বিরাজমান", englishMeaning: "Present, appearing, or found everywhere.", synonyms: ["omnipresent", "pervasive", "universal", "widespread"], antonyms: ["rare", "scarce", "uncommon"], example: "Smartphones have become ubiquitous in modern life.", prefix: "", rootWord: "ubique (everywhere)", suffix: "-ous", mnemonic: "UBIQUITOUS — like UBER, found everywhere.", etymology: "Latin ubique, 'everywhere'.", tags: ["GRE", "IELTS"], difficulty: "hard", isFavorite: true }),
  S({ word: "Venerate", pronunciation: "/ˈven.ər.eɪt/", partOfSpeech: "verb", banglaMeaning: "গভীর শ্রদ্ধা করা; ভক্তি করা", englishMeaning: "To regard with great respect; revere.", synonyms: ["revere", "respect", "honor", "esteem"], antonyms: ["despise", "scorn", "disdain"], example: "Many cultures venerate their elders.", prefix: "", rootWord: "vener (reverence)", suffix: "-ate (to make)", mnemonic: "VENERATE — treat someone like VENUS, a goddess.", etymology: "Latin venerari, 'to adore, revere'.", tags: ["GRE"], difficulty: "hard" }),
  S({ word: "Wary", pronunciation: "/ˈweə.ri/", partOfSpeech: "adjective", banglaMeaning: "সতর্ক; সাবধানী", englishMeaning: "Feeling or showing caution about possible dangers or problems.", synonyms: ["cautious", "careful", "vigilant", "alert"], antonyms: ["careless", "reckless", "trusting"], example: "Be wary of emails asking for your password.", prefix: "", rootWord: "", suffix: "", mnemonic: "WARY → be aWARE.", etymology: "Old English wær, 'aware, cautious'.", tags: ["SAT"], difficulty: "easy" }),
  S({ word: "Zealous", pronunciation: "/ˈzel.əs/", partOfSpeech: "adjective", banglaMeaning: "উদ্যমী; প্রবল উৎসাহী", englishMeaning: "Having or showing great energy or enthusiasm for a cause.", synonyms: ["enthusiastic", "passionate", "fervent", "eager"], antonyms: ["apathetic", "indifferent", "unenthusiastic"], example: "He was a zealous supporter of environmental causes.", prefix: "", rootWord: "zeal (ardor)", suffix: "-ous (full of)", mnemonic: "ZEALOUS people are full of ZEAL.", etymology: "Greek zēlos, 'ardor, jealousy'.", tags: ["GRE"], difficulty: "medium" }),
  S({ word: "Ambiguous", pronunciation: "/æmˈbɪɡ.ju.əs/", partOfSpeech: "adjective", banglaMeaning: "দ্ব্যর্থবোধক; অস্পষ্ট", englishMeaning: "Open to more than one interpretation; not having one obvious meaning.", synonyms: ["unclear", "vague", "equivocal", "obscure"], antonyms: ["clear", "explicit", "unambiguous"], example: "The instructions were ambiguous, so everyone did it differently.", prefix: "ambi- (both)", rootWord: "agere (to drive)", suffix: "-uous", mnemonic: "AMBI = both → it can mean both ways.", etymology: "Latin ambiguus, 'doubtful'.", tags: ["IELTS", "SAT"], difficulty: "medium" }),
  S({ word: "Eloquent", pronunciation: "/ˈel.ə.kwənt/", partOfSpeech: "adjective", banglaMeaning: "বাগ্মী; সুবক্তা", englishMeaning: "Fluent or persuasive in speaking or writing.", synonyms: ["articulate", "expressive", "fluent", "persuasive"], antonyms: ["inarticulate", "tongue-tied", "halting"], example: "She delivered an eloquent speech at the ceremony.", prefix: "e- (out)", rootWord: "loqu (to speak)", suffix: "-ent", mnemonic: "E-LOQU-ENT: speaking out beautifully (loqu = speak).", etymology: "Latin eloqui, 'to speak out'.", tags: ["IELTS"], difficulty: "medium" }),
  S({ word: "Mitigate", pronunciation: "/ˈmɪt.ɪ.ɡeɪt/", partOfSpeech: "verb", banglaMeaning: "প্রশমিত করা; লাঘব করা", englishMeaning: "To make something bad less severe, serious, or painful.", synonyms: ["alleviate", "reduce", "lessen", "ease"], antonyms: ["aggravate", "worsen", "intensify"], example: "Planting trees can help mitigate climate change.", prefix: "", rootWord: "mitis (mild, soft)", suffix: "-ate (to make)", mnemonic: "MITIGATE — put a MITT on the pain to soften it.", etymology: "Latin mitigare, 'to soften'.", tags: ["GRE", "IELTS"], difficulty: "hard" }),
  S({ word: "Procrastinate", pronunciation: "/prəˈkræs.tɪ.neɪt/", partOfSpeech: "verb", banglaMeaning: "গড়িমসি করা; কালক্ষেপণ করা", englishMeaning: "To delay or postpone action; to put off doing something.", synonyms: ["delay", "postpone", "defer", "stall"], antonyms: ["hasten", "expedite", "hurry"], example: "Don't procrastinate — start your assignment today.", prefix: "pro- (forward)", rootWord: "crastinus (of tomorrow)", suffix: "-ate", mnemonic: "PRO + CRAS (tomorrow): pushing everything forward to tomorrow.", etymology: "Latin procrastinare, 'to defer till tomorrow'.", tags: ["IELTS", "SAT"], difficulty: "medium" }),
  S({ word: "Vivid", pronunciation: "/ˈvɪv.ɪd/", partOfSpeech: "adjective", banglaMeaning: "প্রাণবন্ত; উজ্জ্বল ও স্পষ্ট", englishMeaning: "Producing strong, clear images in the mind; intensely bright.", synonyms: ["bright", "colorful", "striking", "graphic"], antonyms: ["dull", "faded", "vague"], example: "She has vivid memories of her childhood village.", prefix: "", rootWord: "viv (to live)", suffix: "-id", mnemonic: "VIV = life (as in 'vivacious'); VIVID = full of life.", etymology: "Latin vividus, 'full of life'.", tags: ["IELTS"], difficulty: "easy" }),
  S({ word: "Inevitable", pronunciation: "/ɪˈnev.ɪ.tə.bəl/", partOfSpeech: "adjective", banglaMeaning: "অনিবার্য; অবশ্যম্ভাবী", englishMeaning: "Certain to happen; unavoidable.", synonyms: ["unavoidable", "certain", "inescapable", "inexorable"], antonyms: ["avoidable", "uncertain", "preventable"], example: "Change is inevitable in every organization.", prefix: "in- (not)", rootWord: "evit (to avoid)", suffix: "-able", mnemonic: "IN-EVIT-ABLE: not able to be avoided.", etymology: "Latin inevitabilis, 'unavoidable'.", tags: ["IELTS", "SAT"], difficulty: "easy" }),
  S({ word: "Altruism", pronunciation: "/ˈæl.tru.ɪ.zəm/", partOfSpeech: "noun", banglaMeaning: "পরার্থপরতা; নিঃস্বার্থ পরোপকার", englishMeaning: "Selfless concern for the well-being of others.", synonyms: ["selflessness", "unselfishness", "generosity", "philanthropy"], antonyms: ["selfishness", "egoism", "greed"], example: "Her altruism inspired the whole community to volunteer.", prefix: "", rootWord: "alter (other)", suffix: "-ism (practice of)", mnemonic: "ALTRU = ALTER = other → caring for others.", etymology: "French altruisme, from Italian altrui 'somebody else'.", tags: ["GRE"], difficulty: "medium" }),
  S({ word: "Cacophony", pronunciation: "/kəˈkɒf.ə.ni/", partOfSpeech: "noun", banglaMeaning: "কর্কশ কোলাহল; বেসুরো শব্দ", englishMeaning: "A harsh, discordant mixture of sounds.", synonyms: ["din", "racket", "noise", "discord"], antonyms: ["harmony", "silence", "euphony"], example: "A cacophony of car horns filled the street.", prefix: "caco- (bad)", rootWord: "phon (sound)", suffix: "-y", mnemonic: "CACO = bad + PHONY = sound → a bad sound.", etymology: "Greek kakophōnia, 'bad sound'.", tags: ["GRE"], difficulty: "hard" }),
];
